version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '2323:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=login
    volumes:
      - login_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '1919:1919'
    volumes:
      - 'login_redis_data:/bitnami/redis/data'

volumes:
  login_pg_data:
  login_redis_data: